# Generated by Django 4.2.15 on 2025-02-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ISIN_number', models.CharField(max_length=20, null=True, unique=True)),
                ('Ticker', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('sector', models.CharField(max_length=200)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
