# Generated by Django 4.2.15 on 2025-02-11 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('asset_type', models.CharField(blank=True, max_length=204, null=True)),
                ('ownership_1', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('water_score', models.FloatField(blank=True, default=0, null=True)),
                ('biodiv_score', models.FloatField(blank=True, default=0, null=True)),
                ('social_score', models.FloatField(blank=True, default=0, null=True)),
                ('owner_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_owner1', to='blog.company')),
                ('owner_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_owner2', to='blog.company')),
                ('owner_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_owner3', to='blog.company')),
            ],
        ),
    ]
